# file: .github/workflows/scheduled-run.yml
# (c) 2025 Asymmetric Effort, LLC. scaldwell@asymmetric-effort.com
name: Scheduled Maintenance

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  verify-gpg-keys:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install GnuPG
        run: sudo apt-get update && sudo apt-get install -y gnupg
      - name: Verify keys
        env:
          GPG_SIGNING_KEY_CI_PRIVATE: ${{ secrets.GPG_SIGNING_KEY_CI_PRIVATE }}
          GPG_SIGNING_KEY_CI_PUBLIC: ${{ secrets.GPG_SIGNING_KEY_CI_PUBLIC }}
        run: python3 scripts/check_gpg_keys.py

  trigger-codeql:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CodeQL workflow
        uses: peter-evans/workflow-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          workflow: codeql.yml
          ref: ${{ github.ref }}
